### ISSUE TITLE
Autoscaling does not run

### ISSUE THREAD

**Issue by Elkoumy** [aws-samples/emr-trino-autoscale#1]
Hi,
First of all, thank you for providing such a great solution to a demanding issue with Trino and EMR.

Our EMR cluster contains one primary node (r6g.4xlarge), 2 core nodes (m6g.2xlarge), and 2 task nodes (m6g.2xlarge). I installed and configured the code from this repository as mentioned in the README file. While monitoring the queries for an hour, I noticed that the code does not add new nodes to the cluster. 

I added so debugging points to the code. I noticed that in the file `TrinoAutoscaler.scala`, you are running three classes: Workers, `ScalingManager`, and `TrinoMetricStore`. The Workers class is running. The daemon is also running on the master node. However, all the debugging loggers inside the `ScalingManager` and `TrinoMetricStores` do not write anything to the logs. 

Could you please elaborate on what can be the reason for that?

Regards,
Gamal

**Comment by ripani-aws** [comment]
Hi Gamal, thank you for reporting this issue. Can you share the configuration that you used in the application.conf for the autoscaling? Besides, have you noticed if this was a sporadic issue or if the problem can constantly be reproduced also on a new cluster? In the meantime I'll try to launch a cluster using the same topology you used to see if I can reproduce the problem in my environment

**Comment by ripani-aws** [comment]
Hi Gamal, I've performed several tests in past few days but I don't see any problem starting the autoscaling. Everything seems working as expected. I also tried different Java versions to build the package but this didn't trigger any problem. Do you still have problems running the autoscaling? If you want, we can have a call to see what's the problem in your environment. If this is the case let me know a mail where I can reach out to you and I'll contact you from my internal amazon mail.

**Comment by ripani-aws** [comment]
closed due to inactivity
