### ISSUE TITLE
Unable to Clone Repo in EC2 (repo not found)

### ISSUE THREAD

**Issue by vjcao** [aws-samples/emr-trino-autoscale#4]
Hi @ripani-aws.

I'm trying to run this clone command from the readme in my EC2 instnace: `git clone https://github.com/ripani-aws/trino-managed-scaling.git && cd trino-managed-scaling`. At first it said that HTTPS cloning wasn't allowed so I tried using PAT method: `git clone https://<your-username>:<your-token>@github.com/ripani-aws/trino-managed-scaling.git`. This method works but I'm getting a `fatal: repository 'https://github.com/ripani-aws/trino-managed-scaling.git/' not found` error. Is there an updated repo URI? Thank you.

**Comment by ripani-aws** [comment]
Hi @vjcao, the repository that you're using is an old one that wasn't updated in the README. The correct repository is `https://github.com/aws-samples/emr-trino-autoscale.git`. I've also updated the README instructions to reflect the change. Thanks for the report
